// Generated by CoffeeScript 1.6.3
(function() {
  var CountyMap, CountyMapControls,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CountyMapControls = (function() {
    function CountyMapControls(map) {
      var changeEvent, controls, races, selectedRace, selectedYear, years;
      controls = d3.select('body').append('div');
      years = controls.append('select');
      years.selectAll('option').data([2010, 2020, 2030, 2040, 2050, 2060]).enter().append('option').attr('value', function(d) {
        return d;
      }).text(function(d) {
        return d;
      });
      races = controls.append('select');
      races.selectAll('option').data(['Total (All race groups)', 'White', 'Black', 'American Indian', 'Asian', 'Native Hawaiian and other Pacific Islander', 'Hispanic or Latino', 'Multi-Race']).enter().append('option').attr('value', function(d) {
        return d;
      }).text(function(d) {
        return d;
      });
      selectedYear = function() {
        return years.node().value;
      };
      selectedRace = function() {
        return races.node().value;
      };
      changeEvent = function() {
        return map.loadPopulationData(selectedYear(), selectedRace());
      };
      years.on('change', changeEvent);
      races.on('change', changeEvent);
    }

    return CountyMapControls;

  })();

  CountyMap = (function() {
    CountyMap.prototype.height = 960;

    CountyMap.prototype.width = 1160;

    CountyMap.prototype.max = 200;

    function CountyMap() {
      this.appendCounties = __bind(this.appendCounties, this);
      var projection,
        _this = this;
      this.appendControls();
      this.svg = d3.select('body').append('svg').attr('width', this.width).attr('height', this.height);
      projection = d3.geo.albers().scale(15000).rotate([122.2500, 0, 0]).center([0, 37.3500]).parallels([36, 35]).translate([this.width / 4, this.height / 2]);
      this.path = d3.geo.path().projection(projection);
      this.colors = d3.scale.linear().domain([0, this.max, 10000]).range(['#fff', '#3498db', '#3498db']);
      d3.json('data/cali.json', function(error, counties) {
        return d3.csv("data/race_by_county.csv", function(error, csv_data) {
          _this.raw_data = csv_data;
          _this.appendCounties(counties);
          _this.appendOutline(counties);
          return _this.loadPopulationData("2010", 'Total (All race groups)');
        });
      });
    }

    CountyMap.prototype.appendControls = function() {
      return new CountyMapControls(this);
    };

    CountyMap.prototype.appendOutline = function(counties) {
      var filter;
      this.svg.append('path').datum(topojson.mesh(counties, counties.objects.california_counties, function(a, b) {
        return a === b && a.id === b.id;
      })).attr('class', 'outline').attr('d', this.path).style('stroke', 'gray').style('stroke-width', '0.5pt').style('fill', 'none');
      filter = this.svg.append('defs').append('filter').attr('id', 'dropshadow');
      filter.append('feGaussianBlur').attr('in', 'SourceAlpha').attr('stdDeviation', 3).attr('result', 'blur');
      filter.append('feOffset').attr('in', 'blur').attr('dx', 2).attr('dy', 2).attr('result', 'offsetBlur');
      filter.append('feComponentTransfer').append('feFuncA').attr('type', 'linear').attr('slope', '0.2');
      return this.svg.append('path').datum(topojson.merge(counties, counties.objects.california_counties.geometries.filter(function(d) {
        return d.properties.bay_area;
      }))).attr('class', 'outline').attr('d', this.path).style('stroke', 'black').style('stroke-width', '2pt').style('fill', 'none');
    };

    CountyMap.prototype.appendCounties = function(counties) {
      var _this = this;
      this.counties = this.svg.selectAll('.county').data(topojson.feature(counties, counties.objects.california_counties).features).enter().append('g').attr('class', '.county');
      this.counties.append('path').attr('class', 'fill').datum(function(d) {
        return d;
      }).attr('d', this.path);
      this.hoverLayer = this.svg.selectAll('.county_hover').data(topojson.feature(counties, counties.objects.california_counties).features).enter().append('g').attr('class', 'tooltip').style('opacity', 0);
      this.hoverLayer.append('path').datum(function(d) {
        return d;
      }).attr('d', this.path).style('stroke', 'black').style('stroke-width', 2).style('fill', 'white').style('fill-opacity', 0);
      this.hoverLayer.append('text').text(function(d) {
        return d.properties.name;
      }).attr('x', function(d) {
        return _this.path.centroid(d)[0];
      }).attr('y', function(d) {
        return _this.path.centroid(d)[1];
      }).attr('text-anchor', 'middle').style('font-family', 'arial').style('font-weight', 'bold').style('font-size', '8pt');
      return this.hoverLayer.on('mouseover', function(d) {
        return d3.select(this).style('opacity', 1);
      }).on('mouseout', function() {
        return d3.select(this).style('opacity', 0);
      });
    };

    CountyMap.prototype.loadPopulationData = function(year, race) {
      var colorWrapper, county, pop, _i, _len, _ref,
        _this = this;
      pop = {};
      _ref = this.raw_data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        county = _ref[_i];
        if (county["YEAR"] === year) {
          pop[county["County"]] = county;
        }
      }
      colorWrapper = function(value, divisor, county) {
        var v;
        v = parseInt(value);
        return _this.colors(v / divisor);
      };
      return this.counties.selectAll('path.fill').transition().style('fill', function(d) {
        return colorWrapper(pop[d.properties.name][race], _this.path.area(d), d.properties.name);
      });
    };

    return CountyMap;

  })();

  new CountyMap;

}).call(this);
